lab2
KirylAkulich1/FrontEndTasks pull request #2
Opened 2021-03-10 07:48 UTC by KirylAkulich1

2021-03-10 18:21 UTC, gmltA requested changes
The mockups are not detailed enough. I can't fully understand what are you showing me.

Also make sure to enlighten yourself about proper `tabindex` usage; lists; `h1`, `h2` and so on.

2021-03-17 17:03 UTC, gmltA requested changes
Ну вы ж нічога амаль не палепшылі...

`h2` не трэба класці ў `p`. З `tabindex` вы я ўвогуле не разумею што робіце.
Старонак для дэктопнай версіі няма.
Дэталізацыя старонак недастатковая.

2021-03-22 13:22 UTC, KirylAkulich1 commented
Please,check mobile version first to see HTML description.

2021-03-23 13:05 UTC, gmltA requested changes
**Settings page** – `h3` каля radio кантрола быць не павінен. Там павінен быць `label`.
На старонцы **Game** усё яшчэ незразумела што з загалоўкамі. Ну пачытайце вы пра іх іерархію і ў якія тэгі яшчэ трэба тэкст абварочваць...

2021-04-24 15:49 UTC, gmltA commented
Усё яшчэ праблемы з тэкстам у вас... Магу прапанаваць <kbd>5</kbd> i не будзем далей змагацца, калi хочаце.

2021-05-06 20:48 UTC, KirylAkulich1 commented
Согласен.Не будем с этой лабой больше змагацца

2021-05-19 14:21 UTC, merged