Fe/lab4
KirylAkulich1/FrontEndTasks pull request #4
Opened 2021-05-11 13:27 UTC by KirylAkulich1

2021-05-11 17:31 UTC, KirylAkulich1 commented
https://kirylakulich1.github.io/FrontEndTasks/fe_lab3/
To navigate to admin panel press SHIFT+TAB anywhere and enter login:superadmin@super.com  password : superadmin

2021-05-12 19:25 UTC, gmltA requested changes

2021-05-12 19:25 UTC, gmltA commented on fe_lab3/css/styles.css
> +  float: right;
Not allowed.

2021-05-12 19:37 UTC, KirylAkulich1 commented on fe_lab3/css/styles.css
> +  float: right;
is this the only place I need to fix to pass lab4?

2021-05-12 19:51 UTC, KirylAkulich1 commented on fe_lab3/css/styles.css
> +  float: right;
Is it the only place I need to fix to pass lab4?

2021-05-13 17:11 UTC, gmltA commented on fe_lab3/css/styles.css
> +  float: right;
If there are other occurrences of `float` then you need to replace them too.

2021-05-13 17:12 UTC, gmltA commented on fe_lab3/css/styles.css
> +  float: right;
But yes, that would be enough to pass.

2021-05-16 14:52 UTC, KirylAkulich1 commented on fe_lab3/css/styles.css
> +  float: right;
fixed

2021-05-18 19:32 UTC, gmltA approved these changes
That's a <kbd>7</kbd>.

2021-05-18 19:43 UTC, KirylAkulich1 commented
Thank you

2021-06-14 12:07 UTC, closed without merging